#!/bin/bash

file="/boitata.ceu"
dir=${PWD}
home=${HOME}

clear

echo "##############################################"
echo "Compilando todo os arquivos e executando o jogo"
date
echo "##############################################"

# As duas expressões a seguir são equivalentes, mas a primeira funciona apenas em algumas versões do linux
#make -C $home/ceu-sdl/ all ceu SRC=$dir$file
cd $home/ceu-sdl/ && make all ceu SRC=$dir$file


