#!/bin/bash

prog="/boitata_debug_2.ceu"

dir=$(pwd)

clear

echo "##############################################"
echo "Compilando todo os arquivos e executando o jogo"
date
echo "##############################################"

cd
cd ceu-sdl
make ceu SRC=$dir$prog all

